### ISSUE TITLE
CC-by-NC-SA 4.0 license does not suit software very well

### ISSUE THREAD

**Issue by carlos22** [netgusto/Pulpy#1]
I think this license [1] is a bad choice for software. Because what is supposed to mean by "non commercial"? Especially in combination with Baikal (where it will be embedded right?). People who want to run it as an addition to their E-Mail service can't do that...

"However, there will always be uses that are challenging to categorize as commercial or noncommercial. CC cannot advise you on what is and is not commercial use. If you are unsure, you should either contact the rights holder for clarification, or search for works that permit commercial uses." [2]

"We recommend against using Creative Commons licenses for software." [3]

[1] https://creativecommons.org/licenses/by-nc-sa/4.0/
[2] https://wiki.creativecommons.org/NonCommercial_interpretation
[3] https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

**Comment by netgusto** [comment]
I am well aware of this.

Commercial use, according to CC: "A commercial use is one primarily intended for commercial advantage or monetary compensation."

> People who want to run it as an addition to their E-Mail service can't do that...

They can, they just have to ask for a license grant, and frankly that's not much to ask if their intent is commercial advantage or monetary compensation.

Please also note that a licence grant does not necessarily imply a license fee.

Anyhow, the license may be opened at any point in the future if we (the rights holder) decide so.
